apiVersion: v1
kind: Service
metadata:
  name: dealership-backend
  labels:
    run: dealership-backend
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    run: dealership-app
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dealership-app
  name: dealership-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership-app
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: dealership-app
        tier: backend
    spec:
      containers:
      - image: us.icr.io/dealership_app_amar/dealership_app:v1
        imagePullPolicy: Always
        name: dealership-app
        ports:
        - containerPort: 8000
          protocol: TCP
      restartPolicy: Always