apiVersion: v1
kind: Service
metadata:
  name: dealership-frontend
  labels:
    run: dealership-frontend
spec:
  #type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    #nodePort: 32500
  selector:
    run: nginx-server
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx-server
  name: dealership-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-server
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx-server
        tier: frontend
    spec:
      containers:
      - image: us.icr.io/dealership_app_amar/nginx-server:v1
        #imagePullPolicy: Always
        name: nginx-server
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always